name: navigatr
description: >-
  The open-source Maps SDK for Flutter. Zero API keys, zero cost.
  High-performance routing, geocoding, autocomplete, and fully customizable
  map rendering powered by OpenStreetMap.
version: 1.0.0
homepage: https://navigatr.dev
repository: https://github.com/touresouleymane/navigatr
issue_tracker: https://github.com/touresouleymane/navigatr/issues
documentation: https://navigatr.dev/docs/flutter

topics:
  - maps
  - openstreetmap
  - geocoding
  - routing
  - navigation

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
