name: mhj_maps
description: >-
  The open-source Maps SDK for Flutter. Zero API keys, zero cost.
  High-performance routing, geocoding, autocomplete, and fully customizable
  map rendering powered by OpenStreetMap.
version: 1.2.3
homepage: https://mhj_maps.mihradj.com
repository: https://github.com/toure5013/mhj-maps
issue_tracker: https://github.com/toure5013/mhj-maps/issues
documentation: https://github.com/toure5013/mhj-maps

topics:
  - maps
  - openstreetmap
  - geocoding
  - routing
  - navigation

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.2.0
  collection: ^1.17.0
  flutter_svg: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
